/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gusrubin.lab.javafxgettingstarted;

import org.junit.jupiter.api.Test;

import org.junit.jupiter.api.Assertions;

class AppTest {
    @Test void appHasAGreeting() {
        Assertions.assertTrue(true);
    }
}
