spring:
  application:
    name: spring-general-lab
  main:
    banner-mode: off
    
  # H2 Config
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: dev
    password: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      #http://localhost:{service-port}/h2-console
    
server:
  port: 8090
  
# Actuator
management:
  endpoints:
    web:
      exposure:
        include:
        - 'info'
        - 'health'
        
springdoc:
  show-actuator: true
    
logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    '[org.springframework]': info
    '[com.zaxxer.hikari]': info
    '[org.hibernate]': info
    '[com.gusrubin.lab.springgenerallab]': info
