spring:
  application:
    name: spring-clean-log
  main:
    banner-mode: off
    
  # PostgreSQL Config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${SYSTEM_DATABASE_NAME}
    username: ${SYSTEM_DATABASE_USER}
    password: ${SYSTEM_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    
server:
  port: 8081
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-exception: false
    include-message: never
  
# Actuator
management:
  endpoints:
    web:
      exposure:
        include:
        - 'info'
        - 'health'      
        
springdoc:
  show-actuator: true
   
logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    '[org.springframework]': off
    '[com.zaxxer.hikari]': error
    '[org.hibernate]': error
    '[com.gusrubin.lab.cleanlog]': info
    